export const TRANSACTION_CATEGORIES = [
  "Não categorizado",
  "Receita de Vendas",
  "Receita de Serviços",
  "Outras Receitas",
  "Salários e Encargos",
  "Fornecedores",
  "Aluguel",
  "Contas de Consumo (Água, Luz, etc.)",
  "Impostos e Taxas",
  "Despesas com Marketing",
  "Despesas com Viagens",
  "Despesas com Veículos",
  "Manutenção e Reparos",
  "Despesas Administrativas",
  "Serviços de Terceiros",
  "Juros e Despesas Bancárias",
  "Investimentos",
  "Amortização/Depreciação",
  "Distribuição de Lucros",
  "Transferência entre Contas",
  "Outras Despesas Operacionais",
];

export const BRAZILIAN_BANKS = [
  "Banco do Brasil S.A.",
  "Caixa Econômica Federal",
  "Itaú Unibanco S.A.",
  "Banco Bradesco S.A.",
  "Banco Santander (Brasil) S.A.",
  "BTG Pactual S.A.",
  "Banco Safra S.A.",
  "Banco Votorantim S.A.",
  "Nu Pagamentos S.A. - Nubank",
  "Banco Inter S.A.",
  "Banco C6 S.A.",
  "Banco Original S.A.",
  "XP Investimentos",
  "Banco Neon S.A.",
  "PagSeguro Internet S.A.",
  "Mercado Pago",
  "Sicoob - Sistema de Cooperativas de Crédito do Brasil",
  "Sicredi - Sistema de Crédito Cooperativo",
  "Outro",
];
